# Generated by Django 4.1.2 on 2022-10-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-date'], 'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['id'], 'verbose_name': 'Сенсор', 'verbose_name_plural': 'Сенсоры'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время проводимых измерений.', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='graduses',
            field=models.FloatField(default=0.0, help_text='Измеряемая температура в цельсиях.', verbose_name='Градус'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measure_data', to='measurement.sensor', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, help_text='Ваше примичание к прибору.', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, default='sensor', help_text='Название модели.', max_length=50, verbose_name='Модель'),
        ),
    ]
